### ISSUE TITLE
Docker image for kafka-connect-mongodb

### ISSUE THREAD

**Issue by mostafaghadimi** [hpgrahsl/kafka-connect-mongodb#100]
Is there any image on docker hub? I have search but I didn't find any image over the internet.

**Comment by hpgrahsl** [comment]
hi @mostafaghadimi! short answer -> no.

somewhat longer answer: it's not really common to provide docker images with single/separate custom connectors pre-installed. instead you typically use docker images for kafka-connect (e.g. like the ones provided by confluent https://hub.docker.com/u/confluentinc/ ) and mount a pre-built connector into the respective installation folder of the container via volumes. since you most likely need several other components as well (zookeeper, kafka, ...) it's better to use at least docker-compose to setup the whole stack. find an example which was used for one of my recent blog post here https://github.com/hpgrahsl/mongodb-kafka-connect-environment/blob/master/docker-compose.yml#L30-L54 

thx again for reaching out!

**Comment by mostafaghadimi** [comment]
Hi @hpgrahsl, I have tried [https://github.com/mongodb/mongo-kafka](kafka) and I saw your name as the main contributor. Whenever I have run the docker-compose file of the official site I face with the following error:

```
Step 3/3 : RUN  confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest
 ---> Running in 8f5be4b90eff
Running in a "--no-prompt" mode 
java.net.UnknownHostException: api.hub.confluent.io 
 
Error: Unknown error 
ERROR: Service 'connect' failed to build: The command '/bin/sh -c confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest' returned a non-zero code: 7
```

I have nothing to do and don't know how to fix this problem. Can you help me. please?

Thanks
