### ISSUE TITLE
How to test connection between kafka and mongodb

### ISSUE THREAD

**Issue by mostafaghadimi** [hpgrahsl/kafka-connect-mongodb#104]
Hi Hans-Peter,

I'm trying to test the docker-env.yml file in the `kafka-connect-mongodb/src/test/resources/docker ` directory. It runs without any error. The question is how to send data using kafka and write it on mongodb collection?

The second thing is that the jar files address in `kafka-connect-container` aren't uploaded on the server. because of the address: ` ../../../../target/kafka-connect-mongodb/`. Would you please upload the jar files?

If you need my docker-compose file it can be found on [stackoverflow](https://stackoverflow.com/questions/57738083/test-kafka-to-mongodb-sink-connector-using-docker).

Thanks,
Mostafa

**Comment by hpgrahsl** [comment]
hi @mostafaghadimi nice to hear you want to give this project a spin :)

the main reason for the docker compose file your are referring to is to provide an environment for very a simple E2E test run during the build. 

1) if you run `docker-compose -f compose-env.yaml up` and everything starts up without issues you should be able to connect to kafka using `localhost:9092` with any producer of your choice or the `kafka-console-producer` in order to publish data to topics. likewise, you should be able to post a sink connector configuration by means of CURL or Postman to `localhost:8083`

2) not quite sure what you mean by the jar file isn't uploaded to the server. what happens is that the folder which contains the build artefact for the sink connector is mounted into the kafka-connect docker container via the volume definition in the compose file. provided that you run the docker-compose file from within the `src/test/resources/docker` folder it should work fine. The relative path that you see is the source folder which points to the `target` folder of the maven build artefact. This gets mounted into the correct folder of the corresponding docker container.

hope this gives you a better understanding about how this is supposed to work. again, this is there for E2E testing. you may want to use a different/better compose env for other things :)

**Comment by mostafaghadimi** [comment]
Hi,

I mean jar file isn't located on the github repository. As you have told, it should be mounted into kafka-connect docker container, but there isn't any file to be mounted! :)  cause I don't know how to build the project using maven. Would you please guide me how to run the project using maven to download the jar files or would you upload the jar files manually?

Thanks,
Mostafa

**Comment by hpgrahsl** [comment]
Oh I see :) 

1) You can build with maven simply by running from `mvn clean package` in the root folder of the project (where the `pom.xml` is located). This should download a bunch of dependencies when you run it first and result in the `target/kafka-connect-monogdb` folder with the jar you need.

2) If for whatever reason you cannot build locally you can get a pre-build artefact in version 1.3.1 (not the latest snapshot from the master branch though) either on maven central or via confluent hub.

**Comment by mostafaghadimi** [comment]
Thank you Hans-Peter,

The only question remained is the following:

I have produced some data using kafka producer but they didn't save on mongodb collection. I need a sample to do so. Would you explain the steps?

**Comment by hpgrahsl** [comment]
Not sure what you exactly mean by that. If you have successfully produced data to a kafka topic you need to run the sink connector simply by sending an HTTP POST request which contains your sink connector configuration of choice to the kafka-connect process. That's it.

You can find e.g. the configuration file for the E2E test (which is essentially only a 1:1 pass-through of the AVRO data that was produced to the kafka topic) in `src/test/resources/config/sink_connector.json`. If you have JSON data in your topics instead of AVRO you choose the appropriate key/value converter settings in the configuration.

**Comment by mostafaghadimi** [comment]
Yes I have created kafka topic, the question is exactly I don't know _what_ and _how_ to put data in POST request. Would you please send a sample to check whether it works or not?

I think it's my last question. Thank you for your warm support! :)

**Comment by mostafaghadimi** [comment]
Hi @hpgrahsl 

I'm looking forward to hearing anything helpful from you. If you could help me, I would be very thankful. I have spend a lot of time resolving these issues and I don't know where to ask my questions except here and from you. 

Thanks,
Mostafa

**Comment by hpgrahsl** [comment]
@mostafaghadimi From what I've seen you are using the wrong URL for you POST request against the Kafka Connect REST API. 

https://docs.confluent.io/current/connect/references/restapi.html#post--connectors

I think it might be very valuable for you to spend some time reading the Kafka Connect documentation. The Link above only discusses the REST API but there is plenty of more interesting stuff to learn about Kafka Connect. It also helps to work with any specific connector like this one :)

**Comment by mostafaghadimi** [comment]
Hi @hpgrahsl 

I have read the documentation carefully and the problem isn't solved. So I decided to implement the sink connection in a different manner. Now it works perfect. 

Thanks for your attention,
Mostafa

**Comment by hpgrahsl** [comment]
Thx @mostafaghadimi for your reply and closing. I'd really like the learn what you did in order to solve your problem. If it's an alternative approach to get your data into mongodb I'd be interested as well. If it's only due to a problem with your docker environment or the wrong REST API usage it would be a pity if you moved away from this approach ... anyway glad to hear you got it working somehow.

**Comment by mostafaghadimi** [comment]
Hi @hpgrahsl 

Sure, I have created [a repository](https://github.com/mostafaghadimi/dockerized-kafka-mongodb-connector) and I have explained what to do in the `README.md` file.

Is there any similar way to connect kafka to redis? 

Thanks,
Mostafa
