### ISSUE TITLE
SerializationException

### ISSUE THREAD

**Issue by andreypp** [hpgrahsl/kafka-connect-mongodb#17]
Hi,

I am following [this blog](https://medium.com/@stephane.maarek/how-to-use-apache-kafka-to-transform-a-batch-pipeline-into-a-real-time-one-831b48a6ad85) post on medium and I'd like to persist data on MongoDB instead of Postgres.

When the connector try to read topics data, an error occurs linke bellow:

`    {
      "state": "FAILED",
      "trace": "org.apache.kafka.connect.errors.DataException: recent-stats io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:96)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:453)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1\nCaused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!\n",
      "id": 2,
      "worker_id": "127.0.1.1:8083"
    }`

But when I run the kakfa-avro-consumer the data is read successfuly.

Anybody have had the same problem?

**Comment by hpgrahsl** [comment]
Hi @andreypp 

Well it's hard to tell without knowing about additional details (e.g. the avro schema of the messages etc., the configuration of the involved connector(s) etc.)

Furthermore, as far as I can see from the stacktrace you posted, the exception happens when connect is trying to convert from AVRO to the connect internal format. So if I'm not mistaken, the error seems to happen before my sink connector even starts to process the data.

Hope you will find out soon what isn't working for you.

**Comment by andreypp** [comment]
Thanks @hpgrahsl 
I just ran the JDBC Connector and it is OK. 
Any tip on how to investigate this issue? (I mean, the conversion from AVRO to connect internal format)

**Comment by hpgrahsl** [comment]
I think the issue in your case might be that most likely the key of your record is just not serialized with AVRO but e.g. plain string or json or something else. then this magic byte error occurs. 

the avro-console-consumer might miss this because it it per default configured to only read the value part of records and would thus miss the key serialization issue.

**Comment by hpgrahsl** [comment]
@andreypp have you found a solution yet? If you need any further help please let me know. Otherwise I would close this issue if that's ok for you

**Comment by andreypp** [comment]
@hpgrahsl Thanks for your attention. You can close the issue, cause I am not working on it anymore. But I hope to come back soon!

**Comment by hpgrahsl** [comment]
@andreypp ok thx. time will tell. let me know if you need anything.
