### ISSUE TITLE
Example for Java 

### ISSUE THREAD

**Issue by AnthonyKoueik** [hpgrahsl/kafka-connect-mongodb#32]
Hello

i have kafka and mongoDb installed and running,
can you help me with a small java class example to run to send messages from MyTopic to Mongo?
( I do not have Confluent , simply kafka)

thank you

**Comment by hpgrahsl** [comment]
Great to hear to you are trying to run the mongodb sink connector! I'm not sure if I correctly understand your question but if you have kafka & mongodb installed and running then you only need to write some data to your topic either by producing records as JSON or AVRO.

**In order to let Kafka Connect do it's job and write messages from a kafka topic to a mongodb collection you do NOT need any code.** All you have to do is run the connector either in standalone or distributed mode with a proper configuration. I'd suggest you:

1) read through the first parts of https://kafka.apache.org/documentation/#connect the official kafka connect docs
2) if possible download Confluent Platform 4.1 and try out Kafka Connect because it's very well documented, much easier to start with and everything you need for this is open source and free of charge. after doing so start with this: https://docs.confluent.io/current/connect/quickstart.html

Finally you should have an easy time to use my connector. Its configuration options are described in detail here https://github.com/hpgrahsl/kafka-connect-mongodb#sink-connector-properties

Let me know if you need anything else. Have fun!

**Comment by AnthonyKoueik** [comment]
hello 

Sorry for my unclear question, i wanted to make test cases from the Java code.
I have read the  https://kafka.apache.org/documentation/#connect and now i have better understanding.

thank you for you time

**Comment by hpgrahsl** [comment]
No worries. Glad to hear that the docs helped :)
