### ISSUE TITLE
Kerberos and ssl/tls support

### ISSUE THREAD

**Issue by aashishkumar0102** [hpgrahsl/kafka-connect-mongodb#48]
Hi,

I want to know if the connector support Kerberos and tls/ssl support?

**Comment by hpgrahsl** [comment]
Hi @aashishkumar0102 !

Thanks for bringing up your question. The sink connector supports everything on a protocol / authentication mechanism that the official MongoDB Java Driver supports.

1) So SSL/TLS yes definitely! You just add the SSL option to the URI connection string in the connector's configuration file.

2) As for Kerberos it depends :)
AFAIK Kerberos is still on Enterprise only feature. Thus, you have to check which version of mongod process you are running in order to know whether or not Kerberos is available for you. The Java Driver however would have support for it of course.

I'd be more than happy if you share a few insights about you use case of this sink connector. Thanks in advance.

**Comment by aashishkumar0102** [comment]
Hi,

Thanks for your quick response !

can you also tell me about how to configure the sink connector for the same like what config parameter to passed in order to change the authentication mechanism from defaults to Kerberos?

can you provide me a detailed configuration doc for both the above as I am not able to get any doc related to that.

Thanks

**Comment by aashishkumar0102** [comment]
Hi,

Thanks For the Quick response,

can you tell me about the configuration docs for the same, like what properties to be mention in

**Comment by hpgrahsl** [comment]
Hi @aashishkumar0102 

You can find a detailed description how you can configure the connection string in the official mongodb docs. https://docs.mongodb.com/manual/reference/connection-string/ All official drivers including the Java Driver used for the connector should support these configuration options.

Good luck :) Again I'd be happy to learn a bit about your concrete use case for the connector.

**Comment by aashishkumar0102** [comment]
Hi,

Our use case is like live data is coming to kafka in different topics and we want each topic to sink data in different collection in mongo also we are using avro based data and defining key and value schema.
and if same data is coming with same key it should update the fields.

so for the above use case can you suggest the appropriate config for your connector?
we want to define _id based on key_schema also.

also what is the benchmark for your connector or can you suggest the connector config if we have to process around 10000 events/s each of size around 100KB?

**Comment by hpgrahsl** [comment]
1) there is currently no option to support multiple different topic <-> collection mappings with a single connector configuration - it's a planned feature but unfortunately not available yet. in case you have a somewhat limited / reasonable number of topics (e.g. 5-20) you can temporarily workaround this by launching multiple connector instances each handling only a single topic. see also this discussion https://github.com/hpgrahsl/kafka-connect-mongodb/issues/45

2) if your _id field is derived from the key record or parts thereof you can easily achieve this by configuring a proper DocumentIdAdder strategy which is documented in the README see https://github.com/hpgrahsl/kafka-connect-mongodb#documentidadder-mandatory

3) the default operation mode of the connector always uses UPSERT semantics based on the resulting _id field. thus, given that you process a new record with the same _id the corresponding mongodb document will get updated accordingly.

4) as for your benchmark question it is by no means possible to give you reasonable and concrete answer since the final throughput performance is depending on so many different factors :) Also I'm not aware of any (standardized) benchmarks for other specific community supported sink connectors. Feel free to send me some pointers in case you know about any.

Irrespective of that, have you done the quick maths for "10.000 events / sec each being 100KB in size"?

Only by looking at the raw data volume this means 1000 MB = 1 GB throughput per sec. Also is this a peak throughput you want to be able to handle or kind of a constant / average data volume to process. The latter would mean something like 864 Mio events and 86 TB per day which would be huge. 

Leaving aside Kafka and the sink connector itself, you would have quite a handful to do in order to be able to handle such a write load/volume database-wise, some sort of "XL sharded mongodb beast cluster" :)

**Comment by aashishkumar0102** [comment]
Hi,

Thank you for the quick response.

we have some different scenario like around a million record would populate in a whole day and average size is 10KB only not 100KB(mistake). and in midnight again all the data the client would replicate all together and all data we have to sink in around 5 minutes, that's why I asked roughly for that much throughput.

**Comment by hpgrahsl** [comment]
Ok I see. What you are describing now has indeed almost nothing in common with your original inquiry ;-) just to make sure if I understood you correctly:

1) you are ingesting about 1 Mio records each having 10KB into Kafka during the day = in total ~10GB data
2) then you want to process these accumulated records starting at midnight within a 5 min window, meaning that you need a throughput of ~ 2GB / min or  ~ 33 MB / sec, in number of records this would be equivalent to 1 Mio / 5 min = 200k / min = 3333 / sec which should be totally doable given a reasonable HW config and proper parallelism.

however, I'm afraid that the only way to really find out is to try it with your AVRO data in your environment and with your deployment configuration :) I'd be interested to hear back from you after your experiments how it worked out for your particular use case. 

Q: why do you not continuously process the data with the connector as it lands in Kafka topics instead of letting it accumulate for a whole day?

**Comment by aashishkumar0102** [comment]
Hi,

some data they will continuously sink and for some they cannot do live as the client is a Bank and they can only replicate in maintenance hours only.

We are testing other connectors also right now, will surely let you know after the testing.

Again, Thank you very much for your quick response and support.

**Comment by aashishkumar0102** [comment]
Can you also explain little what is CDC tool?
