### ISSUE TITLE
Convert CurrentBSONType is DOCUMENT, not when CurrentBSONType is INT32

### ISSUE THREAD

**Issue by mikefrancois** [hpgrahsl/kafka-connect-mongodb#55]
Even if I used 

**distributed.properties**

CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"

**connector config**

 "connector.class":"at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
  	  
  	  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "key.converter.schemas.enable": "false",
          
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "value.converter.schemas.enable": "false",
      

**data**

{ \"name\": \"Anonymous\", \n" +
                    "  \"age\": 42,\n" +
                    "  \"active\": true, \n" +
                    "  \"address\": {\"city\": \"Unknown\", \"country\": \"NoWhereLand\"},\n" +
                    "  \"food\": [\"Austrian\", \"Italian\"],\n" +
                    "  \"data\": [{\"k\": \"foo\", \"v\": 1}],\n" +
                    "  \"lut\": {\"key1\": 12.34, \"key2\": 23.45}\n" +
                    "}

**error**

Caused by: org.bson.BsonInvalidOperationException: readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is INT32.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:692)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
	at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:452)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:81)
	at org.bson.BsonDocument.parse(BsonDocument.java:62)
	at at.grahsl.kafka.connect.mongodb.converter.JsonRawStringRecordConverter.convert(JsonRawStringRecordConverter.java:32)
	at at.grahsl.kafka.connect.mongodb.converter.SinkConverter.convert(SinkConverter.java:44)

**Comment by hpgrahsl** [comment]
hi @mikefrancois !

nice to see that you try to work with the mongodb sink connector :) unfortunately what you report is very limited in information so let me guess right into the blue:

1) I assume the JSON object you posted above as "data" is the value part of the record
2) the problem is most likely related to the key part of your records
3) even if you specified the _StringConverter_ for the key the connector currently expects the String to be valid JSON, which obviously isn't the case. your key might be an INT type so just the number which won't work. what you need to provide is a "wrapping JSON object" e.g. {"k":1234}

I think what you are facing is very similar to this issue #36 - read through this how to solve this by means of configuring a proper SMT.

**Comment by mikefrancois** [comment]
Thank you for your answer @hpgrahsl.
Effectively, my record was not so good and I changed for an INT in my structure.
Everything seems to be ok now.

**Comment by hpgrahsl** [comment]
You are welcome. Glad to hear you got it working. It would be interesting to learn about your particular use case. Would you be willing to share? I'm always looking for user voices / testimonials to feature in the readme.

**Comment by mikefrancois** [comment]
With pleasure.

**Comment by hpgrahsl** [comment]
Great to hear @mikefrancois! I'd be really happy if you could send me a few lines what you are doing with it. In case it's tied to a company use case also feel free to share the name and/or logo. You can check the other two testimonials if you need an inspiration :) THX in advance
