### ISSUE TITLE
Sinking aggregated data does not work

### ISSUE THREAD

**Issue by masihyeganeh** [hpgrahsl/kafka-connect-mongodb#56]
Hi. I have an issue with Sinking data to MongoDB using your code.
I read similar issues like #55 and #36 and I know possible solutions but I couldn't make them work with my situation.
I have a stream that I aggregate values of it within a window using KSQL. here is my query:

```sql
CREATE TABLE WATCHTIME_AGG AS \
 SELECT ID, MAX(progress) AS progress, MAX(position) AS position, MAX(timestamp) AS timestamp \
   FROM WATCHTIME \
   WINDOW TUMBLING (SIZE 1 HOUR) \
   GROUP BY ID;
```

It creates a table which it's ROWKEYs are like this:

- `149988257825337_6696933 : Window{start=1540024620000 end=-}`
- `null_11646895 : Window{start=1540024620000 end=-}`
- `153974245826038_6222197 : Window{start=1540024620000 end=-}`
- `151415963389431_11197398 : Window{start=1540024620000 end=-}`
- `153173851492214_9207426 : Window{start=1540024620000 end=-}`

But it can't be Sinked because of JSON error when key type is JSON:
`com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0x90\n at [Source: (byte[])\"null_12208937\u0000\u0000\u0001f\ufffd\u0007\ufffd\u0000\"; line: 1, column: 19]`

And this error when key type is String:
`org.bson.json.JsonParseException: JSON reader was expecting a value but found 'null_12208937'`

The key should be a valid JSON or Avro if I'm not wrong, but window aggregation won't produce JSON and won't let me change it to a valid one.

What can I do to make it work?
It's a really simple use-case and should be straightforward. But at least I could not make it work.

**Comment by masihyeganeh** [comment]
I also tried hoisting with no success.
```json
{
  "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
  "topics": "WATCHTIME_AGG",
  "mongodb.connection.uri": "mongodb://...?w=1&journal=true",
  "name": "watchtime-mongo",
  "value.converter.schema.registry.url": "http://schema-registry:8081",
  "value.converter.schemas.enable": "false",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schema.registry.url": "http://schema-registry:8081",
  "key.converter.schemas.enable": "false",
  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "mongodb.collection": "watchtime",
  "transforms": "id_to_object",
  "transforms.id_to_object.type": "org.apache.kafka.connect.transforms.HoistField$Key",
  "transforms.id_to_object.field": "id"
}
```

**Comment by hpgrahsl** [comment]
Hi @masihyeganeh thx for getting in touch!

1) the question is how do you want the data of the KTable to be inserted into the MongoDB collection? By that I mean how would a mongodb document look like: would it include the rowkey information as a field, should this even become the _id field in the resulting document? because then you may need further post processors

2) apart from that a plain naive insertion generating new BSON Object Id for each KTable entry in the MongoDB collection should work with a small change only, namely specify the StringConverter for the key part of the sink record like so:

```json
{ ...
"key.converter.schemas.enable": "false",
	  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
... }
```

The rest should be fine from what I've seen. Also there is no need to use schema-registry for this in my opinion.

**Comment by masihyeganeh** [comment]
Thanks for swift reply.
To answer your first question, I'd like to have a mongo collection to store watch time of users for movies in windows. Something like this:
```JSON
{
    "_id": "{user1_movie1_windowStartTime}",
    "user": "user1",
    "movie": "movie1",
    "watchtime": "{aggregated watchtime}",
    ...
}
```

And for the second one, the second error (`org.bson.json.JsonParseException: JSON reader was expecting a value but found 'null_12208937'`) happened when I used `org.apache.kafka.connect.storage.StringConverter` as key converter.

And hoisting didn't make any difference even in error messages

**Comment by hpgrahsl** [comment]
@masihyeganeh 

1) for me the configuration with a StringConverter for key worked fine. I used some different data but the rowkey is also coming from a WINOWED calculation and contained data of similar format than yours. so I'm currently wondering what's the problem at your side. this was my configuration 

```json
{ "name": "ksql-ingest-01",
	"config":
    {
	  "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
	  "topics": "DEMO_KSQL_TABLE",
	  "mongodb.connection.uri": "mongodb://localhost:27017/kafkaconnect?w=1&journal=true",
	  "value.converter.schemas.enable": "false",
	  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
	  "key.converter.schemas.enable": "false",
	  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
	  "mongodb.collection": "demo_ksql_table",
	  "transforms": "id_to_object",
	  "transforms.id_to_object.type": "org.apache.kafka.connect.transforms.HoistField$Key",
	  "transforms.id_to_object.field": "id"
	}
}
```

2) the actual problem here seems to be that the rowkey when generated from windowed calculations is containing a binary structure, which is why the interpretation as string in kafka connect contains non-printable characters. you can see this when you try to e.g. use the console consumer and print the keys of the underlying topic. there are several efforts underway to fix this and besides give rowkeys a well defined semantics. see the following KSQL issues:

- https://github.com/confluentinc/ksql/issues/1497
- https://github.com/confluentinc/ksql/pull/2024

In the meantime you could work around this by e.g. writing your own UDF and do it in KSQL before, or writing you own SMT and let it happen in Connect. Either way if you fix it temporarily on your own you should expect breaking changes starting with CP 5.1+

3) w.r.t to the final _id field for the resulting document I'm wondering why you are wrapping it in '{'...'}' since it's only a string and not valid JSON anyway? Also when you want the _id field to look like this you need to do that in advance in KSQL with string functions or with an SMT since the sink connector itself has no such id generation strategy in place.

I hope this helps!

**Comment by masihyeganeh** [comment]
I appreciate your help man. Thanks for taking time to test it.

1. You mean you have a WINDOWED aggregated stream as a KTable and StringConverter can successfully convert it's binary ROWKEY to a string that can be stored in Mongo? I can't. how it works for you?

2. I was even thinking about a simple hash function that converts ROWKEY containing string and binary to a simple hex string. It will actually solve my problem. Isn't there any hash function or anything similar to it in KSQL?

3. No no, I am using `{` `}`  to show that this field is calculated from those values and is not a constant string. It's not JSON or object. sorry for misleading example.

**Comment by hpgrahsl** [comment]
>     1. You mean you have a WINDOWED aggregated stream as a KTable and StringConverter can successfully convert it's binary ROWKEY to a string that can be stored in Mongo? I can't. how it works for you?

yes the string conversion was done but like I said you get 'garbage characters' and thus a non-usable string representation but it landed in the collection as documents anyway

>    2. I was even thinking about a simple hash function that converts ROWKEY containing string and binary to a simple hex string. It will actually solve my problem. Isn't there any hash function or anything similar to it in KSQL?

you can do it with the string representation that you see on the KSQL CLI. simply add the ROWKEY field to the field list like e.g.

`SELECT ROWKEY AS rk, ... FROM demo_ksql_table`

doing that makes the rowkey part of the value structure of the sink record and then you can refer to it in the sink connector with the proper id generation strategy. Still you will get a representation that matches the one from the KSQL CLI e.g.

`149988257825337_6696933 : Window{start=1540024620000 end=-}`

overall a bit of a hack at best but should be working anyway :)

**Comment by masihyeganeh** [comment]
Thanks man! it's working. But I'm not sure if it is doing what I want or not. I hope it does.
You're great, Thanks

**Comment by hpgrahsl** [comment]
Well the latter is not a good sign... I suggest you better check if it behaves like expected.

**Comment by masihyeganeh** [comment]
Ok, My concern was right. It is not doing what I want.

Here is my config again:
```JSON
{
  "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
  "topics": "WATCH_AGG",
  "mongodb.connection.uri": "mongodb://...",
  "name": "watch-mongo",
  "value.converter.schemas.enable": "false",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schemas.enable": "false",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "mongodb.collection": "watch",
  "transforms": "id_to_object",
  "transforms.id_to_object.type": "org.apache.kafka.connect.transforms.HoistField$Key",
  "transforms.id_to_object.field": "id"
}
```

And it is producing records like this:

```js
/* 1 */
{
    "_id" : ObjectId("5bcf2831471afa0001075f6f"),
    "VID" : NumberLong(7571493),
    "POSITION" : NumberLong(700),
    "PROGRESS" : 0.986749365661122,
    "TIMESTAMP" : NumberLong(1540287039866),
    "ID" : "153207088294975.7571493.",
    "AFCN" : "153207088294975"
}

/* 2 */
{
    "_id" : ObjectId("5bcf2831471afa0001075f7e"),
    "VID" : NumberLong(7571493),
    "POSITION" : NumberLong(700),
    "PROGRESS" : 0.986749365661122,
    "TIMESTAMP" : NumberLong(1540287039866),
    "ID" : "153207088294975.7571493.",
    "AFCN" : "153207088294975"
}

/* 3 */
{
    "_id" : ObjectId("5bcf2831471afa0001075f96"),
    "VID" : NumberLong(7571493),
    "POSITION" : NumberLong(700),
    "PROGRESS" : 0.986749365661122,
    "TIMESTAMP" : NumberLong(1540287039866),
    "ID" : "153207088294975.7571493.",
    "AFCN" : "153207088294975"
}
```

As you can see, it is not updating records with same ID, instead it inserts new records.
the `_id` should be the identical for the records with same ID (if I'm not wrong).
Is it? Am I wrong? I thought it should upsert records in Mongo.

**Comment by masihyeganeh** [comment]
Sorry, my fault.
Thanks for helping.

**Comment by fortinj66** [comment]
This issue still seems to occur with the KSQL 5.1.x branch...

The key on a windowed tables still has binary data embedded making it unusable for JDBC Connect
