### ISSUE TITLE
JsonParseException when sending data from a mosquitto publisher into MongoDb

### ISSUE THREAD

**Issue by shu-bham** [hpgrahsl/kafka-connect-mongodb#64]
I have explained my problem here https://stackoverflow.com/questions/53924735/mongodb-sink-connector-jsonparseexception-json-reader-was-expecting-a-value
 Please help me solve this error

**Comment by shu-bham** [comment]
Thank you for the quick response.
I am using the **publish()** method as described in [Eclipse Paho MQTT Python client library.](https://pypi.org/project/paho-mqtt/#publishing) The publish(topic,payload) method expects the payload _to be string, bytearray, int, float or None_ before sending the message to the topic. Thats the reason I have converted my json object into a json string using json.dumps() before _publishing_.


These are my schemas registered in my schema-registry:
`{"subject":"mqtt.-key","version":1,"id":1,"schema":"\"string\""}`
`{"subject":"mqtt.-value","version":1,"id":2,"schema":"\"bytes\""}`

command used to fetch schemas : 
`curl --silent -X GET http://localhost:8081/subjects/mqtt.-[key|value]/versions/latest` 


This is the output of my **kafka-avro-console-consumer** cli :
`"dist"	"J{\"time\": \"18:50:13.514761\", \"val\": 0}"`

cli command used : 
`bin/kafka-avro-console-consumer --topic mqtt.   --bootstrap-server localhost:9092   --property print.key=true`

Is the output on my kafka-avro-consumer valid for MongoDbSinkConnector to work? Is there anything fishy you can tell? Meanwhile I'll check if their is "plain-string" issue.

**Comment by hpgrahsl** [comment]
Thx for providing further details. What is still not clear to me is what the key for your published records is? The publish method of the python library takes the topic and the payload as a JSON string.

1) according to the schema registry the topic is "mqtt." 
2) but in your python publish call you specify "dist" as the topic
3) in the kafka-avro-console-consumer the key seems to be "dist" ?

anyway if the key of the published records is really "dist" then it's clear why you get the exception. as I wrote above the key of each record needs to be parseable json string otherwise it won't work. so instead of only "dist" you could have a key like e.g. ```"{\"key\": \"dist\"}"```

**Comment by shu-bham** [comment]
Hi. Sorry for the confusion. `dist` is the topic on which I'm publishing my data via Mosquitto and that data is translated to the kafka topic `mqtt.` via the mqtt-source connector file :

`name=MQTT-source`  
`mqtt.topics=dist`
`kafka.topics=mqtt.`


So how can I make `"dist"` to  ` "{\"key\": \"dist\"}" ` ?

**Comment by hpgrahsl** [comment]
The records which you publish to the "dist" topic using mosquitto are then processed i.e. written to the "mqtt." topic by which means? either you can change the key directly during this processing step or you try to employ an Kafka Connect SMT like suggested as a working solution in #36.

**Comment by hpgrahsl** [comment]
Did you have any success yet? If so I'd like to close the issue. If not let me know if you need further help. THX.

**Comment by shu-bham** [comment]
The README  of MQTT-source connector says `The output of this connector is an envelope with all of the properties of the incoming message. If you need the body of the Mqtt message as the value written to the topic in Kakfa, use a Transformation to achieve this.`  
So I am trying to get a working SMT solution. The working transformations given in #36 is not working for me.

**Comment by hpgrahsl** [comment]
Thx for getting back. Of course you cannot simply use the exact same SMT configuration found in #36 for your use case. But the concept to define an SMT with a configuration that fits your message structure / envelope should be the same or at least very similar. Good Luck!

**Comment by shu-bham** [comment]
Hi @hpgrahsl , 
I was able to persist data in mongoDb by changing the converters. Now I am facing one isse. The `whitelist` projection type isn't working for me.

**MongoDbSinkConnector.properties**

`name=MyMongoDbSinkConnector`
`topics=mqtt.`
`tasks.max=1`
`key.converter=org.apache.kafka.connect.json.JsonConverter`
`value.converter=org.apache.kafka.connect.json.JsonConverter`
`key.converter.schemas.enable=false`
`value.converter.schemas.enable=false`
`connector.class=at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector`
`mongodb.connection.uri=mongodb://localhost:27017/sample?w=1&journal=true`
`mongodb.collection=data`
`mongodb.max.num.retries=3`
`mongodb.retries.defer.timeout=5000`
`mongodb.post.processor.chain=at.grahsl.kafka.connect.mongodb.processor.DocumentIdAdder,at.grahsl.kafka.connect.mongodb.processor.WhitelistValueProjector`
`mongodb.[key|value].projection.type=whitelist`
`mongodb.[key|value].projection.list=value.val,key.payload`

Sink **Key** Record : `{"schema":{"type":"string","optional":false},"payload":"dist"}`
Sink **Value** Record : `{"time": "15:00:22.914644", "val": 0}`

Resulting Record in MongoDb : 
`{`
	`"_id" : ObjectId("5c2f27af6c601209897308ac"),`
	`"val" : NumberLong(0),`
	`"time" : "15:00:22.914644"`
`}`

Am I missing something in the properties file ? And how can I debug this behaviour?

**Comment by hpgrahsl** [comment]
The blacklisting and whitelisting of fields has to be applied to the key and value parts of you records separately. So if you want to use whitelisting for your value structure you use the WhitelistValueProjector but you need to specify the WhitelistKeyProjector for whitelisting fields in the key structure. The same holds true for blacklisting. If you want to have it applied for key + value then you need both settings

```
mongodb.key.projection.type=whitelist
mongodb.value.projection.type=whitelist
```

Also you would need the specify both in the ```mongodb.post.processor.chain``` settings.

**Note however that the sink connector only ever writes to MongoDB what is part of the value structure after the applying all post-processors.** If I understand your example from above correctly you want to "copy" the field ```{"payload":"dist"}``` from the key part of the record into the value part. This is currently not supported since it can and should also be done in advance using a proper SMT configuration :)

**Comment by shu-bham** [comment]
Thanks. the Addendum part worked. Now It all comes to the SMT part. Please help me write an SMT for inserting that `key.payload` into `value`. Now thats all I require for moving on my project xD.

**Comment by hpgrahsl** [comment]
Unfortunately it seems there is no ready-made SMT for you based on the current docs see e.g. https://docs.confluent.io/current/connect/transforms/index.html

This basically leaves you with three options:

1.  write a custom SMT
2. write a custom PostProcessor for my MongoDB sink connector. 
3. if neither 1) nor 2) is what you can do, then it would be the easiest to include the field ```"payload":"dist"``` into the value part of the record right from the beginning i.e. you add it to the data that you're then publishing with ```client.publish("dist", json.dumps(data), qos=2)```. doing so allows you to just list the field for the whitelisting in the sink connector configuration.

hope this helps!

**Comment by shu-bham** [comment]
Yes I agree none of the available SMT solves my problem. `3` seems the easiest way to get going with my project. If afterwards time permits, I will try to write a custom PostProcessor for Sink Connector.
