### ISSUE TITLE
Convert String Date or epoch into Mongo ISODate

### ISSUE THREAD

**Issue by jigs031** [hpgrahsl/kafka-connect-mongodb#84]
Hi

We are migrating our existing mongo ingestion processes to Kafka connect. Incoming data has  timestamp and date columns  and wanted to store it as ISODate format.

Below is sample data set

`{
"INGESTION_TS" : NumberLong("1559757225159"), 
"PROCESS_TS" : "2019-06-05T19:53:45.159Z", 
"DEVICE" : "Samsung SCH-I535", 
"DEVICE_MAKE" : "Samsung", 
"DEVICE_MODEL" : "SCH-I535",  "SUBID" : "OWZlNHw5Y2UxNDlkOHw5YWUxNDJkN3w5ZGViNDJ8OTNlNjQ1fDljZWE0MWRhfDk5ZWI0NWRifGZFZEkx",
 "SUCCESS" : "1", 
"TYPE" : "Ad Request", 
"WEBSITE" : "ALTAMOB", 
"WEBSITEID" : "563", 
"WEBSITEURL" : "http://ad-volt.com/", 
"WIDTH" : "300",
 "WIN" : null, 
"ZONEID" : "1228", 
"ZONENAME" : "API"}`

We need to store "INGESTION_TS" and  "PROCESS_TS" should be stored as ISODate format so that existing processes can consume it efficiently without any change. I tried Avro/JSON with our schema but non of them is working.  

Currently Records are processed and produced by KSQL which does not support Date/DateTime logical type yet.  https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#ksql-time-units 
Can someone suggest workaround?

**Comment by hpgrahsl** [comment]
Hi @jigs031!

Very nice of you to reach out. The sink connector itself is able to work with Date/Time fields since it supports AVRO logical types see in the docs here https://github.com/hpgrahsl/kafka-connect-mongodb#logical-types But in order for this to work as expected, the AVRO records and schema thereof need to be appropriate in the first place. Thus, if you find a way to produce your records according to the logical types spec then the sink connector can store them correctly. 

Whether or not you can achieve that with KSQL is something I cannot currently tell. Would have to look it up myself or give it a try but I'm afraid the current features don't directly allow for this kind of date type handling. Maybe you can write a UDF which does the data type conversion for the AVRO fields in question.

**Comment by hpgrahsl** [comment]
@jigs031 did you find the time to check your options with KSQL / UDFs?

a part from that it looks like Kafka Connect's SMTs also cannot really help you out there since the CAST operator doesn't support date/time related casts at the moment see here https://docs.confluent.io/current/connect/transforms/cast.html

another option and probably the easiest one given all the above is to implement a [custom PostProcessor](https://github.com/hpgrahsl/kafka-connect-mongodb#post-processors) for the sink connector. you can take a look at the existing ones and read the docs to learn how this is done. for such a simple case pretty straight forward. to get some inspiration somebody else wrote one for a different purpose [see here](https://github.com/hpgrahsl/kafka-connect-mongodb/issues/16)

**Comment by hpgrahsl** [comment]
@jigs031 any updates on this? if not I'd kindly ask you to close this issue. THX

**Comment by botbiz** [comment]
Hi @hpgrahsl, Im facing the same thing @jigs031 faced, but in my case there's two main differences, the first is that i want to cast `io.debezium.time.Date` and `io.debezium.time.Timestamp` types to `ISODate` type. And the second is that my source is CDC from SQLServer made by Debezium. There's a possible way to do it? The easiest way is really doing a custom PostProcessor?
