### ISSUE TITLE
id startegy

### ISSUE THREAD

**Issue by sourjya123** [hpgrahsl/kafka-connect-mongodb#97]
Hi I have used kafkametadatastrategy for storing kafka key to mongo. But it stores topic+partitionId+offset.

Can we store the topic only instead of all this information?

**Comment by hpgrahsl** [comment]
Hi @sourjya123! Short answer **NO**. Somewhat longer answer: you are referring to the ID strategy and thus the triplet is needed to ensure uniqueness based on Kafka coordinates. Topic alone wouldn't make much sense since you would only be able to insert 1 document into the collection per kafka topic.
